/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'yulia' at '16-7-20 上午11:09' with Gradle 2.8
 *
 * @author yulia, @date 16-7-20 上午11:09
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
